import { celebrate, Joi, Segments } from 'celebrate';
import { AgeUnit, BloodGroupType, LanguageType, MaritalStatus, ReligionType, SexType } from 'endoscopy-shared';

export const CreatePatientValidator = celebrate({
  [Segments.BODY]: Joi.object({
    recordId: Joi.string().trim().allow(null, '').optional(),
    uhid: Joi.string().allow(null, '').optional(),
    firstName: Joi.string().trim().min(1).required(),
    middleName: Joi.string().trim().allow(null, '').optional(),
    lastName: Joi.string().trim().min(1).required(),
    registrationDate: Joi.string().isoDate().optional(),
    caseDate: Joi.string().isoDate().optional(),
    category: Joi.string().trim().allow(null, '').optional(),
    birthDate: Joi.string().isoDate().allow(null, '').optional(),
    age: Joi.number().integer().min(0).allow(null).optional(),
    ageUnit: Joi.string().allow(null, '').optional(),
    sex: Joi.string().valid(...Object.values(SexType)).allow(null, '').optional(),
    wedding: Joi.boolean().optional(),
    hospitalDoctor: Joi.string().trim().allow(null, '').optional(),
    referenceDoctor: Joi.string().trim().allow(null, '').optional(),
    language: Joi.string().valid(...Object.values(LanguageType)).allow(null, '').optional(),
    religion: Joi.string().valid(...Object.values(ReligionType)).allow(null, '').optional(),
    height: Joi.number().allow(null).optional(),
    weight: Joi.number().allow(null).optional(),
    bloodGroup: Joi.string().valid(...Object.values(BloodGroupType)).allow(null).optional(),
    maritalStatus: Joi.string().valid(...Object.values(MaritalStatus)).allow(null).optional(),
    mobile: Joi.string().trim().max(15).required(),
    mobile2: Joi.string().trim().max(15).allow(null, '').optional(),
    office: Joi.string().trim().allow(null, '').optional(),
    email: Joi.string().trim().email().allow(null, '').optional(),
    address: Joi.string().trim().allow(null, '').optional(),
    area: Joi.string().trim().allow(null, '').optional(),
    city: Joi.string().trim().allow(null, '').optional(),
    state: Joi.string().trim().optional(),
    pin: Joi.string().trim().max(6).allow(null, '').optional(),
    nationality: Joi.string().trim().optional(),
    typeOfVisa: Joi.string().trim().allow(null, '').optional(),
    adharCard: Joi.string().trim().max(16).allow(null, '').optional(),
    profileImage: Joi.string().trim().allow(null, '').optional(),
    panCard: Joi.string().trim().max(10).allow(null, '').optional(),
    membershipId: Joi.string().trim().allow(null, '').optional(),
    employeesId: Joi.string().trim().allow(null, '').optional(),
    occupation: Joi.string().trim().allow(null, '').optional(),
    spouseOccupation: Joi.string().trim().allow(null, '').optional(),
    companyName: Joi.string().trim().allow(null, '').optional(),
    education: Joi.string().trim().allow(null, '').optional(),
    yojanaCardNo: Joi.string().trim().allow(null, '').optional(),
    mediclaim: Joi.boolean().optional(),
    remark: Joi.string().trim().allow(null, '').optional(),
    referralTo: Joi.string().trim().allow(null, '').optional(),
    transfer: Joi.string().trim().allow(null, '').optional(),
    branchId: Joi.number().integer().positive().allow(null).optional(),
    organizationId: Joi.number().integer().positive().allow(null).optional(),
  }).required(),
});

export const UpdatePatientValidator = celebrate({
  [Segments.BODY]: Joi.object({
    recordId: Joi.string().trim().allow(null, '').optional(),
    uhid: Joi.string().allow(null, '').optional(),
    firstName: Joi.string().trim().min(1).optional(),
    middleName: Joi.string().trim().allow(null, '').optional(),
    lastName: Joi.string().trim().min(1).optional(),
    registrationDate: Joi.string().isoDate().optional(),
    caseDate: Joi.string().isoDate().optional(),
    category: Joi.string().trim().allow(null, '').optional(),
    birthDate: Joi.string().isoDate().allow(null, '').optional(),
    age: Joi.number().integer().min(0).allow(null).optional(),
    ageUnit: Joi.string().valid(...Object.values(AgeUnit)).allow(null, '').optional(),
    sex: Joi.string().valid(...Object.values(SexType)).allow(null, '').optional(),
    wedding: Joi.boolean().optional(),
    hospitalDoctor: Joi.string().trim().allow(null, '').optional(),
    referenceDoctor: Joi.string().trim().allow(null, '').optional(),
    language: Joi.string().valid(...Object.values(LanguageType)).allow(null, '').optional(),
    religion: Joi.string().valid(...Object.values(ReligionType)).allow(null, '').optional(),
    height: Joi.number().allow(null).optional(),
    weight: Joi.number().allow(null).optional(),
    bloodGroup: Joi.string().valid(...Object.values(BloodGroupType)).allow(null, '').optional(),
    maritalStatus: Joi.string().valid(...Object.values(MaritalStatus)).allow(null, '').optional(),
    mobile: Joi.string().trim().max(15).optional(),
    mobile2: Joi.string().trim().max(15).allow(null, '').optional(),
    office: Joi.string().trim().allow(null, '').optional(),
    email: Joi.string().trim().email().allow(null, '').optional(),
    address: Joi.string().trim().allow(null, '').optional(),
    area: Joi.string().trim().allow(null, '').optional(),
    city: Joi.string().trim().allow(null, '').optional(),
    state: Joi.string().trim().optional(),
    pin: Joi.string().trim().max(6).allow(null, '').optional(),
    nationality: Joi.string().trim().optional(),
    typeOfVisa: Joi.string().trim().allow(null, '').optional(),
    adharCard: Joi.string().trim().max(16).allow(null, '').optional(),
    profileImage: Joi.string().trim().allow(null, '').optional(),
    panCard: Joi.string().trim().max(10).allow(null, '').optional(),
    membershipId: Joi.string().trim().allow(null, '').optional(),
    employeesId: Joi.string().trim().allow(null, '').optional(),
    occupation: Joi.string().trim().allow(null, '').optional(),
    spouseOccupation: Joi.string().trim().allow(null, '').optional(),
    companyName: Joi.string().trim().allow(null, '').optional(),
    education: Joi.string().trim().allow(null, '').optional(),
    yojanaCardNo: Joi.string().trim().allow(null, '').optional(),
    mediclaim: Joi.boolean().optional(),
    remark: Joi.string().trim().allow(null, '').optional(),
    referralTo: Joi.string().trim().allow(null, '').optional(),
    transfer: Joi.string().trim().allow(null, '').optional(),
    branchId: Joi.number().integer().positive().allow(null).optional(),
    organizationId: Joi.number().integer().positive().allow(null).optional(),
  })
    .min(1)
    .required(),
});

export const PatientIdParamValidator = celebrate({
  [Segments.PARAMS]: Joi.object({
    id: Joi.number().integer().positive().required(),
  }),
});
