import { prisma } from "../../config/database";

const patient_register = [
    {
        "recordId": '',
        "uhid": "UHID100001",
        "firstName": "Priya",
        "middleName": "R",
        "lastName": "Sharma",
        "registrationDate": "2026-05-10",
        "caseDate": "2026-05-10",
        "category": "OPD",
        "birthDate": "1995-03-18",
        "age": 31,
        "ageUnit": "Years",
        "sex": "Female",
        "hospitalDoctor": "Dr. Neha Patel",
        "referenceDoctor": "Dr. Rakesh Mehta",
        "language": "Hindi",
        "religion": "Hindu",
        "height": 165.2,
        "weight": 58.4,
        "bloodGroup": "O+",
        "maritalStatus": "Single",
        "mobile": "9876543201",
        "email": "priya.sharma@example.com",
        "address": "Satellite Road",
        "area": "Satellite",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "380015",
        "nationality": "India",
        "occupation": "Designer",
        "education": "MBA",
        "mediclaim": true,
        "remark": "Allergy history available",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100002",
        "firstName": "Rahul",
        "middleName": "K",
        "lastName": "Patel",
        "registrationDate": "2026-05-10",
        "caseDate": "2026-05-10",
        "category": "IPD",
        "birthDate": "1988-11-12",
        "age": 38,
        "ageUnit": "Years",
        "sex": "Male",
        "hospitalDoctor": "Dr. Amit Shah",
        "referenceDoctor": "Dr. Jignesh Modi",
        "language": "Gujarati",
        "religion": "Hindu",
        "height": 172,
        "weight": 78,
        "bloodGroup": "B+",
        "maritalStatus": "Married",
        "mobile": "9876543202",
        "email": "rahul.patel@example.com",
        "address": "Nikol",
        "area": "Nikol",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "382350",
        "nationality": "India",
        "occupation": "Engineer",
        "education": "B.Tech",
        "mediclaim": true,
        "remark": "Diabetic patient",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100003",
        "firstName": "Sneha",
        "middleName": "M",
        "lastName": "Joshi",
        "registrationDate": "2026-05-09",
        "caseDate": "2026-05-09",
        "category": "OPD",
        "birthDate": "1999-07-21",
        "age": 27,
        "ageUnit": "Years",
        "sex": "Female",
        "hospitalDoctor": "Dr. Pooja Desai",
        "referenceDoctor": "Dr. Bharat Shah",
        "language": "Gujarati",
        "religion": "Hindu",
        "height": 160,
        "weight": 54,
        "bloodGroup": "A+",
        "maritalStatus": "Single",
        "mobile": "9876543203",
        "email": "sneha.joshi@example.com",
        "address": "Bopal",
        "area": "Bopal",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "380058",
        "nationality": "India",
        "occupation": "Teacher",
        "education": "M.Com",
        "mediclaim": false,
        "remark": "Regular checkup",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100004",
        "firstName": "Amit",
        "middleName": "S",
        "lastName": "Trivedi",
        "registrationDate": "2026-05-08",
        "caseDate": "2026-05-08",
        "category": "Emergency",
        "birthDate": "1985-01-14",
        "age": 41,
        "ageUnit": "Years",
        "sex": "Male",
        "hospitalDoctor": "Dr. Ravi Mehta",
        "referenceDoctor": "Dr. Kunal Vyas",
        "language": "Hindi",
        "religion": "Hindu",
        "height": 175,
        "weight": 83,
        "bloodGroup": "AB+",
        "maritalStatus": "Married",
        "mobile": "9876543204",
        "email": "amit.trivedi@example.com",
        "address": "Maninagar",
        "area": "Maninagar",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "380008",
        "nationality": "India",
        "occupation": "Businessman",
        "education": "MBA",
        "mediclaim": true,
        "remark": "BP issue",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100005",
        "firstName": "Kajal",
        "middleName": "P",
        "lastName": "Mehta",
        "registrationDate": "2026-05-07",
        "caseDate": "2026-05-07",
        "category": "OPD",
        "birthDate": "2000-02-10",
        "age": 26,
        "ageUnit": "Years",
        "sex": "Female",
        "hospitalDoctor": "Dr. Nidhi Shah",
        "referenceDoctor": "Dr. Alpesh Patel",
        "language": "Gujarati",
        "religion": "Jain",
        "height": 158,
        "weight": 50,
        "bloodGroup": "O-",
        "maritalStatus": "Single",
        "mobile": "9876543205",
        "email": "kajal.mehta@example.com",
        "address": "Gota",
        "area": "Gota",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "382481",
        "nationality": "India",
        "occupation": "Student",
        "education": "BCA",
        "mediclaim": false,
        "remark": "Migraine issue",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100006",
        "firstName": "Vikram",
        "middleName": "D",
        "lastName": "Singh",
        "registrationDate": "2026-05-06",
        "caseDate": "2026-05-06",
        "category": "IPD",
        "birthDate": "1979-06-18",
        "age": 47,
        "ageUnit": "Years",
        "sex": "Male",
        "hospitalDoctor": "Dr. Ketan Joshi",
        "referenceDoctor": "Dr. Rajesh Sharma",
        "language": "Hindi",
        "religion": "Sikh",
        "height": 180,
        "weight": 88,
        "bloodGroup": "B-",
        "maritalStatus": "Married",
        "mobile": "9876543206",
        "email": "vikram.singh@example.com",
        "address": "Navrangpura",
        "area": "Navrangpura",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "380009",
        "nationality": "India",
        "occupation": "Manager",
        "education": "MBA",
        "mediclaim": true,
        "remark": "Heart patient",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100007",
        "firstName": "Neha",
        "middleName": "T",
        "lastName": "Parmar",
        "registrationDate": "2026-05-05",
        "caseDate": "2026-05-05",
        "category": "OPD",
        "birthDate": "1993-09-22",
        "age": 33,
        "ageUnit": "Years",
        "sex": "Female",
        "hospitalDoctor": "Dr. Hiral Shah",
        "referenceDoctor": "Dr. Amit Trivedi",
        "language": "Gujarati",
        "religion": "Hindu",
        "height": 162,
        "weight": 57,
        "bloodGroup": "A-",
        "maritalStatus": "Married",
        "mobile": "9876543207",
        "email": "neha.parmar@example.com",
        "address": "Chandkheda",
        "area": "Chandkheda",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "382424",
        "nationality": "India",
        "occupation": "HR",
        "education": "MHRM",
        "mediclaim": true,
        "remark": "Thyroid treatment",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100008",
        "firstName": "Rakesh",
        "middleName": "L",
        "lastName": "Yadav",
        "registrationDate": "2026-05-04",
        "caseDate": "2026-05-04",
        "category": "Emergency",
        "birthDate": "1982-04-16",
        "age": 44,
        "ageUnit": "Years",
        "sex": "Male",
        "hospitalDoctor": "Dr. Jay Patel",
        "referenceDoctor": "Dr. Vivek Shah",
        "language": "Hindi",
        "religion": "Hindu",
        "height": 177,
        "weight": 81,
        "bloodGroup": "O+",
        "maritalStatus": "Married",
        "mobile": "9876543208",
        "email": "rakesh.yadav@example.com",
        "address": "Vastral",
        "area": "Vastral",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "382418",
        "nationality": "India",
        "occupation": "Driver",
        "education": "12th",
        "mediclaim": false,
        "remark": "Accident case",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100009",
        "firstName": "Pooja",
        "middleName": "A",
        "lastName": "Bhatt",
        "registrationDate": "2026-05-03",
        "caseDate": "2026-05-03",
        "category": "OPD",
        "birthDate": "1997-12-11",
        "age": 29,
        "ageUnit": "Years",
        "sex": "Female",
        "hospitalDoctor": "Dr. Meenal Shah",
        "referenceDoctor": "Dr. Alpesh Joshi",
        "language": "Gujarati",
        "religion": "Hindu",
        "height": 164,
        "weight": 56,
        "bloodGroup": "B+",
        "maritalStatus": "Single",
        "mobile": "9876543209",
        "email": "pooja.bhatt@example.com",
        "address": "Thaltej",
        "area": "Thaltej",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "380054",
        "nationality": "India",
        "occupation": "Accountant",
        "education": "B.Com",
        "mediclaim": true,
        "remark": "Skin allergy",
        "isActive": true
    },
    {
        "recordId": '',
        "uhid": "UHID100010",
        "firstName": "Harsh",
        "middleName": "N",
        "lastName": "Dave",
        "registrationDate": "2026-05-02",
        "caseDate": "2026-05-02",
        "category": "IPD",
        "birthDate": "1991-05-27",
        "age": 35,
        "ageUnit": "Years",
        "sex": "Male",
        "hospitalDoctor": "Dr. Ravi Shah",
        "referenceDoctor": "Dr. Nilesh Patel",
        "language": "Gujarati",
        "religion": "Hindu",
        "height": 170,
        "weight": 76,
        "bloodGroup": "AB-",
        "maritalStatus": "Married",
        "mobile": "9876543211",
        "email": "harsh.dave@example.com",
        "address": "Memnagar",
        "area": "Memnagar",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin": "380052",
        "nationality": "India",
        "occupation": "Developer",
        "education": "MCA",
        "mediclaim": true,
        "remark": "Kidney stone",
        "isActive": true
    }
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const run = async (): Promise<void> => {
    try {
        const patientRegisterData = patient_register.map((patient) => ({
            ...patient,
        }));
        await prisma.patientRegistration.createMany({
            data: patientRegisterData,
        });
        console.log(`✅ Seeded ${patientRegisterData.length} patient register records.`);
        process.exit(0);
    } catch (error) {
        console.error('❌ Patient register seeder failed', error);
        process.exit(1);
    }
};

void run();