import { AgeUnit, BloodGroupType, LanguageType, MaritalStatus, ReligionType, SexType } from "endoscopy-shared";

export interface ICreatePatient {
  recordId?: string;
  uhid?: string | null;
  firstName: string;
  middleName?: string | null;
  lastName: string;
  registrationDate?: string;
  caseDate?: string;
  category?: string | null;
  birthDate?: string | null;
  age?: number;
  ageUnit?: AgeUnit;
  sex?: SexType;
  wedding?: boolean;
  hospitalDoctor?: string | null;
  referenceDoctor?: string | null;
  language?: LanguageType;
  religion?: ReligionType;
  height?: number | null;
  weight?: number | null;
  bloodGroup?: BloodGroupType | null;
  maritalStatus?: MaritalStatus | null;
  mobile: string;
  mobile2?: string | null;
  office?: string | null;
  email?: string | null;
  address?: string | null;
  area?: string | null;
  city?: string | null;
  state?: string;
  pin?: string | null;
  nationality?: string;
  typeOfVisa?: string | null;
  adharCard?: string | null;
  profileImage?: string | null;
  panCard?: string | null;
  membershipId?: string | null;
  employeesId?: string | null;
  occupation?: string | null;
  spouseOccupation?: string | null;
  companyName?: string | null;
  education?: string | null;
  yojanaCardNo?: string | null;
  mediclaim?: boolean;
  remark?: string | null;
  referralTo?: string | null;
  transfer?: string | null;
  branchId?: number | null;
  organizationId?: number | null;
  resourceInfo?: string | null;
  createdBy?: number | null;
  updatedBy?: number | null;
  createdByAdmin?: number | null;
  updatedByAdmin?: number | null;
}

export interface IUpdatePatient {
  firstName?: string;
  middleName?: string | null;
  lastName?: string;
  registrationDate?: string;
  caseDate?: string;
  category?: string | null;
  birthDate?: string | null;
  age?: number;
  ageUnit?: AgeUnit;
  sex?: SexType;
  wedding?: boolean;
  hospitalDoctor?: string | null;
  referenceDoctor?: string | null;
  language?: LanguageType;
  religion?: ReligionType;
  height?: number | null;
  weight?: number | null;
  bloodGroup?: BloodGroupType | null;
  maritalStatus?: MaritalStatus | null;
  mobile?: string;
  mobile2?: string | null;
  office?: string | null;
  email?: string | null;
  address?: string | null;
  area?: string | null;
  city?: string | null;
  state?: string;
  pin?: string | null;
  nationality?: string;
  typeOfVisa?: string | null;
  adharCard?: string | null;
  profileImage?: string | null;
  panCard?: string | null;
  membershipId?: string | null;
  employeesId?: string | null;
  occupation?: string | null;
  spouseOccupation?: string | null;
  companyName?: string | null;
  education?: string | null;
  yojanaCardNo?: string | null;
  mediclaim?: boolean;
  remark?: string | null;
  referralTo?: string | null;
  transfer?: string | null;
  branchId?: number | null;
  organizationId?: number | null;
  resourceInfo?: string | null;
  updatedBy?: number | null;
  updatedByAdmin?: number | null;
}
